### ISSUE TITLE
헬스커넥트 로직 수정 및 연동 API 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#108]
## 🛠 Issue

헬스커넥트 관련 로직을 수정한다.

## 📝 To-do

- [x] 헬스커넥트 화면 로직 수정
- [x] 헬스커넥트 연동 API 구현
- [x] 헬스커넥트 등록 API null 처리
- [x] 헬스커넥트 등록 API 성공 반환 값 받으면 화면 전환
