### ISSUE TITLE
Logging할 정보 추가

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#117]
## 🛠 Issue

Logging에 유저 관련 정보 등을 추가한다.

## 📝 To-do

- [x] 홈 API Response에 userLog 추가
- [x] 전체 logging에 appVersion 추가
- [x] 혈당, 체중, 운동, 칼로리 로깅에 정보 추가
- [x] 회원가입 관련 로깅 처리
- [x] Exposure 로깅 추가
- [x] logVersion 2로 업데이트
- [x] logging API 헤더 token 제거
