### ISSUE TITLE
포인트 적립, 등록 기능 수정

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#119]
## 🛠 Issue

기존 UI에 text로 적어 놓은 포인트 적립 방법을 서버에서 받아온 값들로 대체하고, 포인트 등록 UI에 이름과 서비스 평가 의견을 추가한다.

## 📝 To-do

- [x] 포인트 적립 방법 UI 수정
- [x] 포인트 적립 방법 API Response 수정
- [x] 포인트 등록 UI 수정
- [x] 포인트 등록 API 수정
