### ISSUE TITLE
FCM 알림 관련 기능 수정

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#136]
## 🛠 Issue

FCM 알림과 관련된 기능을 수정하고, version 1.0.8로 업데이트한다.

## 📝 To-do

- [x] FCM 권한 설정 기능 구현
- [x] Intro API 변경
- [x] 알림 목록 관련 API 문제 해결
- [x] version 1.0.8로 업데이트
