### ISSUE TITLE
Feat: 혈당, 체중, 운동 삭제 기능

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#139]
## 🛠 Issue

혈당, 체중, 운동 데이터 삭제 기능을 구현한다.

## 📝 To-do

- [ ] 혈당 삭제 UI 구현
- [ ] 혈당 삭제 기능 구현
- [ ] 체중 삭제 UI 구현
- [ ] 체중 삭제 기능 구현
- [ ] 운동 삭제 UI 구현
- [ ] 운동 삭제 기능 구현
