### ISSUE TITLE
헬스커넥트 관련 Logging 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#152]
## 🛠 Issue

헬스커넥트 기능과 관련된 Logging을 구현한다.

## 📝 To-do

- [x] 연동하기 버튼 클릭 여부 Logging 구현
- [x] 헬스커넥트 설정 방법 안내 화면 Logging 구현
- [x] 헬스커넥트 설정 방법 안내 화면 스크롤 내린 여부 측정
- [x] 헬스커넥트 페이지로 돌아왔을 때 헬스커넥트 연동 여부 구현
