### ISSUE TITLE
혈당, 운동, 체중 관련 UI/UX 개선

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#156]
## 🛠 Issue

혈당과 운동 화면과 관련된 UI/UX를 개선한다.

## 📝 To-do

- [x] 혈당 추가 이후 EditText 초기화
- [x] 운동 시간 선택 10분 간격으로 수정
- [x] 체중 초기값 0 말고 빈 값으로 수정, 0 입력 막기
- [x] 걸음수 초기값 0 말고 빈 값으로 수정
- [x] 운동 0시간 0분일 때 API 요청 막기
