### ISSUE TITLE
회원가입 UI, View model 책임 분리

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#16]
## 🛠 Issue

회원가입 관련 fragment에 모두 들어있던 UI 관련 로직을 View model의 역할에 맞춰 분리한다.

## 📝 To-do

SignupDiagnosisFragment
- [x] year spinner에 들어가는 list - view model에 정의
- [x] 색상 정보 - view model에 정의
- [x] diagnosisFlag - view model에 Flow로 정의
