### ISSUE TITLE
회원가입 Server Driven UI 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#160]
## 🛠 Issue

회원가입 중 앱을 나가려고 할 때, Server에서 보내주는 text를 통해 이탈 방지 팝업창을 제공한다.

## 📝 To-do

- [x] 회원가입 이탈 방지 팝업창 구현
- [x] Server에서 받아온 값으로 text 구현
- [x] 사용자가 나가는 시점에 팝업창 제공
