### ISSUE TITLE
Intro API 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#2]
## 🛠 Issue

모듈화에 따라 Intro API를 구현해 서버와의 테스트 진행

## 📝 To-do

- [x] 모듈 분리
- [x] BaseActivity, BaseFragment 구현
- [x] NetworkModule (Retrofit) 구현
- [x] Intro API 구현
- [x] Application 파일 추가
