### ISSUE TITLE
혈당 화면 UI 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#23]
## 🛠 Issue

혈당 화면 UI를 구현한다.

## 📝 To-do

- [x] 혈당 화면 UI 구현
- [x] 혈당 추가하기 버튼 클릭시 추가하기 UI 보여주기
- [x] Recylcerview 구현
- [x] Recylcerview 클릭 시 UI 변경 구현
- [x] 혈당 기준 정보 Dialog 구현
