### ISSUE TITLE
혈압, 수면 피드백 화면 삭제 & 도전 탭 -> 식단 탭

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#31]
## 🛠 Issue

기획 변경으로 인해 혈압 및 수면 피드백 화면을 삭제하고, 기존의 도전 tab을 식단 tab으로 변경한다.

## 📝 To-do

- [x] 혈압 화면 삭제
- [x] 수면 화면 삭제
- [x] Home 화면 UI 수정
- [x] Home Viewmodel로 통일
- [x] 하단 바 도전 -> 식단으로 변경
- [x] 조언 -> 가이드 로 명칭 변경
