### ISSUE TITLE
로그인, 회원가입 관련 리팩토링

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#43]
## 🛠 Issue

PR #28 에 대한 리팩토링 진행.
멘토님 코드리뷰를 반영해서 로그인, 회원가입과 관련된 부분들에 대한 리팩토링을 진행한다.

## 📝 To-do

- [x] 에러 Enum 처리
- [x] 상수 처리
- [x] Flag - null 처리
- [x] 자동 로그인 로직 변경
