### ISSUE TITLE
운동 화면, 혈당 화면 UI 수정

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#45]
## 🛠 Issue

운동 화면에서 운동 종류가 추가됨으로써 UI 수정이 필요하다.
혈당 화면에서 수정하기 버튼을 추가해아한다.

## 📝 To-do

- [x] 운동 화면 UI 구현
- [x] 운동 화면 수정하기 UI 구현
- [x] 혈당 화면 수정하기 버튼 추가
- [x] 혈당 화면 추가하기 버튼 클릭시 추가 View 숨기기
