### ISSUE TITLE
하단바 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#5]
## 🛠 Issue

navigation과 BottomNavigationView를 활용해서 하단바를 구현한다.

## 📝 To-do

- [x] HomeFragment, HomeViewModel 생성
- [x] ChartFragment, ChartViewModel 생성
- [x] ChallengeFragment, ChallengeViewModel 생성
- [x] MypageFragment, MypageViewModel 생성
- [x] bottom navigation 구현
