### ISSUE TITLE
헬스커넥트 연동 데이터 및 로직 정리

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#51]
## 🛠 Issue

기획 변경에 따라 헬스커넥트에서 받아오는 데이터를 정리하고, 기기 연동 화면을 구현한다.

## 📝 To-do

- [x] 헬스커넥트 받아오는 데이터 정리
- [x] API 로직, 화면 로직 정리
- [x] Intro에서 받아온 시간부터 데이터 받아오기
