### ISSUE TITLE
헬스커넥트 연동 안내 UI 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#53]
## 🛠 Issue

헬스커넥트 연동 방법을 안내하는 UI를 구현한다.

## 📝 To-do

- [x] 헬스커넥트 연동 안내 UI 구현
- [x] 헬스커넥트 연동 안내 팝업 구현
- [x] 헬스커넥트 연동 안한 유저에게 홈 화면에 버튼 제공 후 팝업 실행
