### ISSUE TITLE
홈 화면 혈당 가이드, 혈당 화면 오늘의 가이드 UI 변경

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#55]
## 🛠 Issue

홈 화면의 혈당 가이드와 혈당 화면의 오늘의 가이드를 그래프 대신 아이콘으로 변경한다.

## 📝 To-do

- [x] 혈당 가이드 Recyclerview Adapter 만들기
- [x] 홈화면 혈당 가이드 수정
- [x] 혈당화면 오늘의 가이드 수정
