### ISSUE TITLE
혈당 화면 조회 API 연동

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#57]
## 🛠 Issue

혈당 전체 화면 조회 API를 연동한다.

## 📝 To-do

- [x] 혈당 오늘의 가이드 Recyclerview에 view model 추가 및 data binding 적용
- [x] 혈당 각각 가이드 Recyclerview에 view model 추가 및 data binding 적용
- [x] 혈당 전체 화면 조회 API 연동
- [x] 서버 배포 완료되면 테스트 하기
- [x] data 있으면 '오늘 혈당을 추가해보세요 !' 숨기기
- [x] 혈당 오늘의 가이드 값 없으면 Recyclerview에서 보여주지 말기 -> UI 상 더 좋은 회색 배경으로 변경
