### ISSUE TITLE
헬스커넥트 데이터 입력 API 연동

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#58]
## 🛠 Issue

헬스커넥트에서 받아온 데이터를 헬스커넥트 데이터 입력 API를 통해 백엔드에 전송한다.

## 📝 To-do

- [x] Intro -> Splash로 파일 이름 변경
- [x] 헬스커넥트 데이터 입력 API 연동
- [x] 헬스커넥트에 받아온 값 -> 서버에 보내는 형식으로 변경
- [x] 생성 날짜 처리
- [x] 혈당 - 시간 type 처리
- [x] 운동 - 운동명, 운동 시간 처리
- [x] 각각 list 받아오는 것 비동기 처리
- [x] 서버 배포 후 테스트
