### ISSUE TITLE
회원가입 성공 시 MainActivity로 화면 전환

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#61]
## 🛠 Issue

회원가입 성공 시 MainActivity로의 화면 전환을 구현한다.

## 📝 To-do

- [x] SignupViewModel에 화면 전환 Flow 정의
- [x] 성공시 HttpResponseStatus.OK emit
- [x] 성공일 경우 Intent 처리
