### ISSUE TITLE
체중 조회 API 연동

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#69]
## 🛠 Issue

체중 조회 API를 연동해서 화면에 나타낸다.

## 📝 To-do

- [x] 체중 조회 API 구현
- [x] data binding 구현
- [x] bar 수치 구현
- [x] 서버 배포 이후 테스트
