### ISSUE TITLE
건강차트 조회 API 연동

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#72]
## 🛠 Issue

건강차트 조회 API를 연동한다.

## 📝 To-do

- [x] 건강차트 조회 API 연동
- [x] UI에 따라 시작 날짜, 끝 날짜 변환
- [x] API Response 그래프에 적용
- [x] 서버 배포 후 테스트
