### ISSUE TITLE
홈 화면 API 연동

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#74]
## 🛠 Issue

홈 화면 API를 연동한다.

## 📝 To-do

- [x] 홈 화면 API 연동
- [x] 혈당 Recyclerview 구현, data binding
- [x] 체중 bar, data binding
- [x] 운동 data binding
- [x] 알람 상태 표시 구현
- [x] 날짜 별 연동 구현
