### ISSUE TITLE
포인트 화면 UI 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#79]
## 🛠 Issue

포인트 관련 화면들의 UI를 구현한다.

## 📝 To-do

- [x] 포인트 메인 페이지 UI 구현 (Activity)
- [x] 전화번호 입력 페이지 UI 구현
- [x] 내역 확인 페이지 UI 구현
- [x] 신청 완료 페이지 UI 구현
