### ISSUE TITLE
포인트 화면 API 연동

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#81]
## 🛠 Issue

포인트 화면과 관련된 API를 연결한다.

## 📝 To-do

- [x] 포인트 내역 조회 API 연동
- [x] 포인트 등록 API 연동
- [x] 포인트 관련 화면들에서 view model을 통한 데이터 전달
- [ ] 서버 배포 후 테스트 진행
