### ISSUE TITLE
Logging 라이브러리 구현

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#86]
## 🛠 Issue

Logging 라이브러리 모듈을 구현하고, 각 화면에 맞는 로깅을 구현한다.

## 📝 To-do

- [ ] logging 라이브러리 모듈 추가 (Builder 패턴 사용)
- [ ] domain에 logging Scheme 구현
- [ ] presentation에서 logging 구현
- [ ] 혈당, 체중, 운동, 칼로리 클릭 logging 구현
- [ ] 혈당 머문 시간 logging 구현
