### ISSUE TITLE
포인트 서버 연동 테스트 및 수정

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#88]
## 🛠 Issue

포인트 서버 배포 이후 테스트를 실행하고, 안되는 부분을 수정한다.

## 📝 To-do

- [ ] 포인트 조회 API, 등록 API 서버 연동 테스트
- [ ] 포인트 조회 API 서버에 맞게 변수명 수정
- [ ] 기프티콘 Recyclerview 클릭시 색상 변경 수정
- [ ] 포인트 부족시 클릭 안되게 처리
