### ISSUE TITLE
알림 목록 화면 UI 구현, API 연동

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#94]
## 🛠 Issue

알림 목록 확인 화면 UI를 구현하고, API를 연동한다.

## 📝 To-do

- [x] 알림 목록 화면 UI 구현
- [x] 알림 목록 조회 API 연동
- [x] 알림 확인 API 연동
