### ISSUE TITLE
닉네임 중복확인 버튼 추가

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#96]
## 🛠 Issue

회원가입 화면에서 닉네임 중복 확인 버튼을 추가하고 API 통신 로직을 변경한다.

## 📝 To-do

- [x] 닉네임 중복확인 버튼 추가
- [x] 버튼 클릭 시 API 호출
- [x] 응답에 따라 Text, Button 디자인 변경
