### ISSUE TITLE
데이터가 null일 때 UI 처리

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#98]
## 🛠 Issue

data가 null일 때 비어 있는 UI를 처리한다.

## 📝 To-do

- [x] 혈당 화면 오늘의 가이드 Text 추가
- [x] 체중 화면 오늘의 가이드 Text 추가
- [x] 운동 화면 걸음수 Text 추가, 오늘의 운동 입력창 축소하기
- [x] 건강 차트 그래프 4개 Text 추가
