### ISSUE TITLE
건강차트 UI 수정

### ISSUE THREAD

**Issue by cyjadela** [co-niverse/dangjang-android#99]
## 🛠 Issue

혈당 차트에서 최소값에 대한 막대 그래프 색상을 변경한다.

## 📝 To-do

- [x] 혈당 최소 그래프 막대 색상 변경
- [x] LabelFormatter 에러 해결
- [x] 한자리수 날짜 0 제거하기
